### ISSUE TITLE
Clarify which versions of services files are used in production

### ISSUE THREAD

**Issue by bpow** [iobio/minion#16]
The services files in this repo are different from the corresponding services files in the [minion-services](https://github.com/iobio/minion-services) repository. It looks like the latter are more recent.

It is confusing to have two sets of similar but different service files. Maybe minion-services could be set up as a dependency and/or git submodule such that the relevant files could be pulled in but would only have one canonical source?

**Comment by chmille4** [comment]
Yep it is confusing and yes the minion-services repo is the more up to date source for service definition files.

I just removed all services from the services repo.
